version: '3.7'

services:

  app:
    build: .
    container_name: UsersWS
    hostname: app
    restart: unless-stopped
    volumes:
      - ./src:/var/www/html
    ports:
      - 8000:80

networks:
  default:
