version: '3.7'

services:

  app:
    build: .
    container_name: UsersWS
    hostname: app
    restart: unless-stopped
    volumes:
      - ./src:/var/www/html
    ports:
      - 8001:80
      - 3306:3306

networks:
  default:
