version: '3.7'

services:

  app:
    build: .
    container_name: UsersWS
    environment:
      - BASTION1_SSH_PUBLIC_KEY=local
      - BASTION2_SSH_PUBLIC_KEY=local
    hostname: app
    restart: unless-stopped
    volumes:
      - ./src:/var/www/html
    ports:
      - 8003:80

networks:
  default:
